/* tslint:disable */
/* eslint-disable */
/**
 * LeakSignal LeakScanner
 * API for LeakSignal LeakScanner
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: max@leaksignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BillingDetails200Response
 */
export interface BillingDetails200Response {
    /**
     * URL to open in a new tab
     * @type {string}
     * @memberof BillingDetails200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the BillingDetails200Response interface.
 */
export function instanceOfBillingDetails200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BillingDetails200ResponseFromJSON(json: any): BillingDetails200Response {
    return BillingDetails200ResponseFromJSONTyped(json, false);
}

export function BillingDetails200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingDetails200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function BillingDetails200ResponseToJSON(value?: BillingDetails200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
    };
}

