/* tslint:disable */
/* eslint-disable */
/**
 * LeakSignal LeakScanner
 * API for LeakSignal LeakScanner
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: max@leaksignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnterPayment200Response
 */
export interface EnterPayment200Response {
    /**
     * Secret for embedded stripe page
     * @type {string}
     * @memberof EnterPayment200Response
     */
    client_secret?: string;
    /**
     * Stripe public API key
     * @type {string}
     * @memberof EnterPayment200Response
     */
    stripe_token?: string;
}

/**
 * Check if a given object implements the EnterPayment200Response interface.
 */
export function instanceOfEnterPayment200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EnterPayment200ResponseFromJSON(json: any): EnterPayment200Response {
    return EnterPayment200ResponseFromJSONTyped(json, false);
}

export function EnterPayment200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnterPayment200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'client_secret': !exists(json, 'client_secret') ? undefined : json['client_secret'],
        'stripe_token': !exists(json, 'stripe_token') ? undefined : json['stripe_token'],
    };
}

export function EnterPayment200ResponseToJSON(value?: EnterPayment200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'client_secret': value.client_secret,
        'stripe_token': value.stripe_token,
    };
}

