/* tslint:disable */
/* eslint-disable */
/**
 * LeakSignal LeakScanner
 * API for LeakSignal LeakScanner
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: max@leaksignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnterPaymentRequest
 */
export interface EnterPaymentRequest {
    /**
     * URL of page to redirect back to if the embedded frame navigates away
     * @type {string}
     * @memberof EnterPaymentRequest
     */
    return_url?: string;
}

/**
 * Check if a given object implements the EnterPaymentRequest interface.
 */
export function instanceOfEnterPaymentRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EnterPaymentRequestFromJSON(json: any): EnterPaymentRequest {
    return EnterPaymentRequestFromJSONTyped(json, false);
}

export function EnterPaymentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnterPaymentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'return_url': !exists(json, 'return_url') ? undefined : json['return_url'],
    };
}

export function EnterPaymentRequestToJSON(value?: EnterPaymentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'return_url': value.return_url,
    };
}

