/* tslint:disable */
/* eslint-disable */
/**
 * LeakSignal LeakScanner
 * API for LeakSignal LeakScanner
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: max@leaksignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthCheck200Response
 */
export interface HealthCheck200Response {
    /**
     * 
     * @type {boolean}
     * @memberof HealthCheck200Response
     */
    db?: boolean;
}

/**
 * Check if a given object implements the HealthCheck200Response interface.
 */
export function instanceOfHealthCheck200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HealthCheck200ResponseFromJSON(json: any): HealthCheck200Response {
    return HealthCheck200ResponseFromJSONTyped(json, false);
}

export function HealthCheck200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthCheck200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'db': !exists(json, 'db') ? undefined : json['db'],
    };
}

export function HealthCheck200ResponseToJSON(value?: HealthCheck200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'db': value.db,
    };
}

