/* tslint:disable */
/* eslint-disable */
/**
 * LeakSignal LeakScanner
 * API for LeakSignal LeakScanner
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: max@leaksignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Logout200Response
 */
export interface Logout200Response {
    /**
     * 
     * @type {string}
     * @memberof Logout200Response
     */
    logout_url?: string;
}

/**
 * Check if a given object implements the Logout200Response interface.
 */
export function instanceOfLogout200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Logout200ResponseFromJSON(json: any): Logout200Response {
    return Logout200ResponseFromJSONTyped(json, false);
}

export function Logout200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Logout200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'logout_url': !exists(json, 'logout_url') ? undefined : json['logout_url'],
    };
}

export function Logout200ResponseToJSON(value?: Logout200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'logout_url': value.logout_url,
    };
}

