/* tslint:disable */
/* eslint-disable */
/**
 * LeakSignal LeakScanner
 * API for LeakSignal LeakScanner
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: max@leaksignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OidcFetch200Response
 */
export interface OidcFetch200Response {
    /**
     * 
     * @type {string}
     * @memberof OidcFetch200Response
     */
    auth_url?: string;
}

/**
 * Check if a given object implements the OidcFetch200Response interface.
 */
export function instanceOfOidcFetch200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OidcFetch200ResponseFromJSON(json: any): OidcFetch200Response {
    return OidcFetch200ResponseFromJSONTyped(json, false);
}

export function OidcFetch200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OidcFetch200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'auth_url': !exists(json, 'auth_url') ? undefined : json['auth_url'],
    };
}

export function OidcFetch200ResponseToJSON(value?: OidcFetch200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'auth_url': value.auth_url,
    };
}

