/* tslint:disable */
/* eslint-disable */
/**
 * LeakSignal LeakScanner
 * API for LeakSignal LeakScanner
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: max@leaksignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RiskItemAnalysisSummaryScriptBodyAnalysis
 */
export interface RiskItemAnalysisSummaryScriptBodyAnalysis {
    /**
     * 
     * @type {string}
     * @memberof RiskItemAnalysisSummaryScriptBodyAnalysis
     */
    timestamp?: string;
    /**
     * 
     * @type {string}
     * @memberof RiskItemAnalysisSummaryScriptBodyAnalysis
     */
    status?: string;
}

/**
 * Check if a given object implements the RiskItemAnalysisSummaryScriptBodyAnalysis interface.
 */
export function instanceOfRiskItemAnalysisSummaryScriptBodyAnalysis(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RiskItemAnalysisSummaryScriptBodyAnalysisFromJSON(json: any): RiskItemAnalysisSummaryScriptBodyAnalysis {
    return RiskItemAnalysisSummaryScriptBodyAnalysisFromJSONTyped(json, false);
}

export function RiskItemAnalysisSummaryScriptBodyAnalysisFromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskItemAnalysisSummaryScriptBodyAnalysis {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timestamp': !exists(json, 'timestamp') ? undefined : json['timestamp'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function RiskItemAnalysisSummaryScriptBodyAnalysisToJSON(value?: RiskItemAnalysisSummaryScriptBodyAnalysis | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'timestamp': value.timestamp,
        'status': value.status,
    };
}

