/* tslint:disable */
/* eslint-disable */
/**
 * LeakSignal LeakScanner
 * API for LeakSignal LeakScanner
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: max@leaksignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RiskItemAnalysisSummaryBlockListAnalysis } from './RiskItemAnalysisSummaryBlockListAnalysis';
import {
    RiskItemAnalysisSummaryBlockListAnalysisFromJSON,
    RiskItemAnalysisSummaryBlockListAnalysisFromJSONTyped,
    RiskItemAnalysisSummaryBlockListAnalysisToJSON,
} from './RiskItemAnalysisSummaryBlockListAnalysis';
import type { RiskItemAnalysisSummaryJavascriptRiskAnalysis } from './RiskItemAnalysisSummaryJavascriptRiskAnalysis';
import {
    RiskItemAnalysisSummaryJavascriptRiskAnalysisFromJSON,
    RiskItemAnalysisSummaryJavascriptRiskAnalysisFromJSONTyped,
    RiskItemAnalysisSummaryJavascriptRiskAnalysisToJSON,
} from './RiskItemAnalysisSummaryJavascriptRiskAnalysis';
import type { RiskItemAnalysisSummaryScriptBodyAnalysis } from './RiskItemAnalysisSummaryScriptBodyAnalysis';
import {
    RiskItemAnalysisSummaryScriptBodyAnalysisFromJSON,
    RiskItemAnalysisSummaryScriptBodyAnalysisFromJSONTyped,
    RiskItemAnalysisSummaryScriptBodyAnalysisToJSON,
} from './RiskItemAnalysisSummaryScriptBodyAnalysis';

/**
 * 
 * @export
 * @interface RiskItemAnalysisSummary
 */
export interface RiskItemAnalysisSummary {
    /**
     * 
     * @type {RiskItemAnalysisSummaryJavascriptRiskAnalysis}
     * @memberof RiskItemAnalysisSummary
     */
    javascriptRiskAnalysis: RiskItemAnalysisSummaryJavascriptRiskAnalysis;
    /**
     * 
     * @type {RiskItemAnalysisSummaryBlockListAnalysis}
     * @memberof RiskItemAnalysisSummary
     */
    blockListAnalysis: RiskItemAnalysisSummaryBlockListAnalysis;
    /**
     * 
     * @type {RiskItemAnalysisSummaryScriptBodyAnalysis}
     * @memberof RiskItemAnalysisSummary
     */
    scriptBodyAnalysis?: RiskItemAnalysisSummaryScriptBodyAnalysis;
}

/**
 * Check if a given object implements the RiskItemAnalysisSummary interface.
 */
export function instanceOfRiskItemAnalysisSummary(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "javascriptRiskAnalysis" in value;
    isInstance = isInstance && "blockListAnalysis" in value;

    return isInstance;
}

export function RiskItemAnalysisSummaryFromJSON(json: any): RiskItemAnalysisSummary {
    return RiskItemAnalysisSummaryFromJSONTyped(json, false);
}

export function RiskItemAnalysisSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskItemAnalysisSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'javascriptRiskAnalysis': RiskItemAnalysisSummaryJavascriptRiskAnalysisFromJSON(json['javascriptRiskAnalysis']),
        'blockListAnalysis': RiskItemAnalysisSummaryBlockListAnalysisFromJSON(json['blockListAnalysis']),
        'scriptBodyAnalysis': !exists(json, 'scriptBodyAnalysis') ? undefined : RiskItemAnalysisSummaryScriptBodyAnalysisFromJSON(json['scriptBodyAnalysis']),
    };
}

export function RiskItemAnalysisSummaryToJSON(value?: RiskItemAnalysisSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'javascriptRiskAnalysis': RiskItemAnalysisSummaryJavascriptRiskAnalysisToJSON(value.javascriptRiskAnalysis),
        'blockListAnalysis': RiskItemAnalysisSummaryBlockListAnalysisToJSON(value.blockListAnalysis),
        'scriptBodyAnalysis': RiskItemAnalysisSummaryScriptBodyAnalysisToJSON(value.scriptBodyAnalysis),
    };
}

