/* tslint:disable */
/* eslint-disable */
/**
 * LeakSignal LeakScanner
 * API for LeakSignal LeakScanner
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: max@leaksignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RiskAssessmentRequestScriptsInner
 */
export interface RiskAssessmentRequestScriptsInner {
    /**
     * 
     * @type {string}
     * @memberof RiskAssessmentRequestScriptsInner
     */
    url?: string;
}

/**
 * Check if a given object implements the RiskAssessmentRequestScriptsInner interface.
 */
export function instanceOfRiskAssessmentRequestScriptsInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RiskAssessmentRequestScriptsInnerFromJSON(json: any): RiskAssessmentRequestScriptsInner {
    return RiskAssessmentRequestScriptsInnerFromJSONTyped(json, false);
}

export function RiskAssessmentRequestScriptsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskAssessmentRequestScriptsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function RiskAssessmentRequestScriptsInnerToJSON(value?: RiskAssessmentRequestScriptsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
    };
}

