/* tslint:disable */
/* eslint-disable */
/**
 * LeakSignal LeakScanner
 * API for LeakSignal LeakScanner
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: max@leaksignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Website
 */
export interface Website {
    /**
     * 
     * @type {number}
     * @memberof Website
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Website
     */
    url?: string;
    /**
     * 
     * @type {number}
     * @memberof Website
     */
    user_id?: number;
    /**
     * 
     * @type {string}
     * @memberof Website
     */
    created_at?: string;
}

/**
 * Check if a given object implements the Website interface.
 */
export function instanceOfWebsite(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WebsiteFromJSON(json: any): Website {
    return WebsiteFromJSONTyped(json, false);
}

export function WebsiteFromJSONTyped(json: any, ignoreDiscriminator: boolean): Website {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'user_id': !exists(json, 'user_id') ? undefined : json['user_id'],
        'created_at': !exists(json, 'created_at') ? undefined : json['created_at'],
    };
}

export function WebsiteToJSON(value?: Website | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'url': value.url,
        'user_id': value.user_id,
        'created_at': value.created_at,
    };
}

