/* tslint:disable */
/* eslint-disable */
/**
 * LeakSignal LeakScanner
 * API for LeakSignal LeakScanner
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: max@leaksignal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebsiteScan
 */
export interface WebsiteScan {
    /**
     * 
     * @type {number}
     * @memberof WebsiteScan
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof WebsiteScan
     */
    website_id: number;
    /**
     * 
     * @type {string}
     * @memberof WebsiteScan
     */
    created_at: string;
    /**
     * 
     * @type {string}
     * @memberof WebsiteScan
     */
    started_at?: string;
    /**
     * 
     * @type {string}
     * @memberof WebsiteScan
     */
    finished_at?: string;
    /**
     * 
     * @type {object}
     * @memberof WebsiteScan
     */
    results?: object;
}

/**
 * Check if a given object implements the WebsiteScan interface.
 */
export function instanceOfWebsiteScan(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "website_id" in value;
    isInstance = isInstance && "created_at" in value;

    return isInstance;
}

export function WebsiteScanFromJSON(json: any): WebsiteScan {
    return WebsiteScanFromJSONTyped(json, false);
}

export function WebsiteScanFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebsiteScan {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'website_id': json['website_id'],
        'created_at': json['created_at'],
        'started_at': !exists(json, 'started_at') ? undefined : json['started_at'],
        'finished_at': !exists(json, 'finished_at') ? undefined : json['finished_at'],
        'results': !exists(json, 'results') ? undefined : json['results'],
    };
}

export function WebsiteScanToJSON(value?: WebsiteScan | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'website_id': value.website_id,
        'created_at': value.created_at,
        'started_at': value.started_at,
        'finished_at': value.finished_at,
        'results': value.results,
    };
}

